## Author: Blake Conrad
### Least Cost Algorithm
<hr>
<hr>

### Libraries
<hr>

In [1]:
import numpy as np
import sys

### Data Structures and Setup
<hr>

In [160]:
_NUM_SUPPLIERS = 3
_NUM_DEMANDS = 4

S = [15,25,5]

D = [5,15,15,10]


# E.g., the first row represents the cost from source1 to [demand1, demand2, demand3]
C = [[10,0,20,11],
     [12,7,9,20],
     [0,14,16,18]]


# I.e., When you meet supply/demand the row/column becomes 1 (satisfied)
B = [[0 for j in range(_NUM_DEMANDS)] 
        for i in range(_NUM_SUPPLIERS)]


# I.e., A matrix of decision variables; how many units should we send from supplyi to demandj?
X = [["na" for j in range(_NUM_DEMANDS)] for i in range(_NUM_SUPPLIERS)]

def printSetup():
    print(":::::     PRINTING SETUP     :::::")
    print("Number of Suppliers: ")
    print(_NUM_SUPPLIERS)
    print("Number of Demanders: ")
    print(_NUM_DEMANDS)
    print("S: ")
    print(S)
    print("D:")
    print(D)
    print("C: ") 
    print(np.matrix(C))
    print("B:")
    print(np.matrix(B))
    print("X:")
    print(np.matrix(X))

printSetup()

:::::     PRINTING SETUP     :::::
Number of Suppliers: 
3
Number of Demanders: 
4
S: 
[15, 25, 5]
D:
[5, 15, 15, 10]
C: 
[[10  0 20 11]
 [12  7  9 20]
 [ 0 14 16 18]]
B:
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
X:
[['na' 'na' 'na' 'na']
 ['na' 'na' 'na' 'na']
 ['na' 'na' 'na' 'na']]


### Least Cost Algorithm Implementation


In [161]:
# Arguments:
#  1. (S) Supply List; decreases to meet demands
#  2. (D) Demand List; decreases as supply is found
#  3. (C) Cost Matrix; baseline reference for moving
#  4. (B) Boolean Matrix; eliminates duplicate routes once optimalities are found
#  5. (X) Decision Variable Matrix; determines optimal amounts of units to ship given cost.
# 
# Return:
#  - integer value representing the least cost from M Suppliers to N Demanders
#
# NOTES: 
#  - X Should be filled with N.A
#  - X Should be of shape (len(S), len(D))
def LeastCostAlgorithm(S, D, C, B, X, debug=False):
    
    while(not(all([s == 0 for s in S]) and all([d == 0 for d in D]))):
    
        # Variables
        min_tmp=9999
        min_i=0
        min_j=0

        # Get the minimum cost; tie-breaking is arbitrary
        for i in range(len(C)):
            for j in range(len(C[i])):
                if ((C[i][j] < min_tmp) and (B[i][j] != 1)):
                    min_tmp = C[i][j]
                    min_i = i
                    min_j = j

        # Subtract min of S[i] D[j] from both
        amount = min(S[min_i], D[min_j])
        S[min_i] = S[min_i] - amount
        D[min_j] = D[min_j] - amount

        # See which is zero, 
        if S[min_i] == 0:
            B[min_i] = [1 for j in range(_NUM_DEMANDS)]
        else:
            for i in range(_NUM_SUPPLIERS):
                for j in range(_NUM_DEMANDS):
                    if j == min_j:
                        B[i][j] = 1

        # Fill X[i][j] with the value subtracted
        X[min_i][min_j] = amount


        if debug:
            print("SUPPLY AND DEMAND NOT EMPTY")
            print("S:")
            print(S)
            print("D:")
            print(D)
            print("M:")
            print(np.matrix(M))
            print("C:")
            print(np.matrix(C))
            print("X:")
            print(np.matrix(X))


    if debug:
        print("SUPPLY AND DEMAND EMPTY")
        
        
    results=[]
    for i in range(len(X)):
        for j in range(len(X[i])):
            if X[i][j] != 'na':
                results.append(X[i][j]*C[i][j])
    results = sum(results)
    return X, results


In [163]:
LeastCostAlgorithm(S, D, C, B, X, debug=False)

([['na', 15, 'na', 'na'], [0, 0, 15, 10], [5, 'na', 'na', 'na']], 335)